### ISSUE TITLE
Not able to get any of the 3 possible adapters working

### ISSUE THREAD

**Issue by smankine** [nolanlawson/pouchdb-adapter-cordova-sqlite#42] opened 2017-03-22 08:28 UTC
Hi there, I have a problem that I haven't been able to resolve

My ionic app currently works with standard idb adapter ( new PouchDB('db')), however sometimes it stops working because of quota exceeded exceptions. This is the reason I'm looking into these other adapters. 

I've installed the demo from https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite-demo
and running it on android (which is the only target platform). I've done the following tests:

Test 1 :no plugin installed: 
	-demo says PouchDB error: you must install a SQLite plugin in order for PouchDB to work on this platform." 
	-the demo does correctly run, would it then be reverting to to another adapter type behind the scenes?
	-db.adapter prints out 'cordova-sqlite'
	-I've added db.info() into the demo code which then returns result.adapter ='websql' ... is this a bug? I assume websql is the real adapter in this case

Test 2: cordova-plugin-sqlite-2 : 
	-demo works with no errors
	-db.adapter prints out 'cordova-sqlite'
	-db.info() -> result.adapter returns 'websql' 
	-when I use it in my own app it's not working and when I print out the adapter (from db.info().then) it says "websql". 
	-I have a PouchDB.replicate and PouchDB.sync in my code, do these need to be passed with the adapter too?
	-I've seen recommendations for not using this plugin for android so I guess I should not be using this anyway

Test 3: cordova-plugin-websql: 
	-both demo and my own app say "PouchDB error: you must install a SQLite plugin in order for PouchDB to work on this platform." 
	-The demo does work though, 
	-db.adapter prints out 'cordova-sqlite'-
	-db.info() -> result.adapter returns 'websql'

Test 4: cordova-sqlite-storage: demo says ""WebSQL threw an error", demo not working

I've tried the demo as it was downloaded but also by replacing the pouchdb.js with the latest pouchdb-6.1.2.min.js and latest pouchdb.cordova-sqlite.js

any ideas?

**Comment by nolanlawson** [comment] 2017-03-22 16:31
I think `db.info() -> result.adapter` always returns websql. I admit I don't remember.

cordova-plugin-sqlite-2 is the recommended one, because it's the one I wrote. I don't recommend it for Android because Android doesn't have the same storage limits as iOS.

cordova-plugin-websql is for Windows devices IIRC.

The way to know if it's actually storing data in SQLite is to check the filesystem and see if SQLite files are being written to. I'm sorry there's no easier way.

Based on your description it sounds like you are worried because of warning messages and/or the adapter saying "websql" but you haven't confirmed where the data is actually being written – WebSQL or SQLite. Is that correct?

BTW you may want to try StackOverflow for these kinds of questions. :)

**Comment by nolanlawson** [comment] 2017-03-22 16:46
Either that or the slack channel which is always very active: http://slack.pouchdb.com

**Comment by nolanlawson** [comment] 2017-03-22 16:56
OK I just confirmed `db.info() => info.adapter` gives the wrong answer. this is a bug that will be fixed in https://github.com/pouchdb/pouchdb/pull/6346

**Comment by smankine** [comment] 2017-03-23 04:29
Thanks for your quick answer. I didn't check the file system yet.  I haven't played much with native databases in general so I didn't realise which ones were appropriate for which platforms. Maybe something you could add on your documentation page about the adapters (https://pouchdb.com/adapters.html) ?

In any case when I enable the cordova-plugin-sqlite-2 plugin my app doesn't work anymore. I might post another question about it after I do some further testing

**Comment by nolanlawson** [comment] 2017-03-23 16:44
Hi, after you posted your issue, I went back and created a fully working demo using PouchDB v6: https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite-demo

If you run the steps, it will work, using `cordova-plugin-sqlite-2`. Please let me know if this helps. Also please reopen if there is truly a bug that need resolving. Thanks!

**Closed by nolanlawson** 2017-03-23 16:44 UTC

**Comment by smankine** [comment] 2017-03-24 02:17
Thanks a lot! I'll have a test. If any issues, I'll post the questions to stakcoverflow, slack etc

**Comment by nolanlawson** [comment] 2017-03-24 16:39
Great, thanks! :)
